package com.mahmoud.ledger.application.service;

import com.mahmoud.ledger.application.port.in.CreateAccountCommand;
import com.mahmoud.ledger.application.port.in.CreateAccountUseCase;
import com.mahmoud.ledger.application.port.in.PostTransactionCommand;
import com.mahmoud.ledger.application.port.in.PostingCommand;
import com.mahmoud.ledger.application.port.in.PostTransactionUseCase;
import com.mahmoud.ledger.application.port.in.RetrieveAccountUseCase;
import com.mahmoud.ledger.application.port.in.TransferFundsCommand;
import com.mahmoud.ledger.application.port.in.TransferFundsUseCase;
import com.mahmoud.ledger.application.port.out.AccountPort;
import com.mahmoud.ledger.application.port.out.TransactionPort;
import com.mahmoud.ledger.domain.model.Account;
import com.mahmoud.ledger.domain.model.Money;
import com.mahmoud.ledger.domain.model.Posting;
import com.mahmoud.ledger.domain.model.Transaction;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class LedgerApplicationService
        implements CreateAccountUseCase, PostTransactionUseCase, RetrieveAccountUseCase, TransferFundsUseCase {

    private final AccountPort accountPort;
    private final TransactionPort transactionPort;

    @Override
    @Transactional
    public UUID createAccount(CreateAccountCommand command) {
        UUID id = UUID.randomUUID();
        Account account = Account.create(id, command.name(), command.currency());
        accountPort.save(account);
        return id;
    }

    @Override
    public Account getAccount(UUID accountId) {
        return accountPort.load(accountId)
                .orElseThrow(() -> new IllegalArgumentException("Account not found"));
    }

    @Override
    @Transactional
    public UUID postTransaction(PostTransactionCommand command) {
        // 1. Create Transaction Domain Object (ID generated by Factory)
        Transaction transaction = Transaction.create(command.description());

        // 2. Add Postings and Validate
        for (PostingCommand postingCmd : command.postings()) {
            Money money = Money.of(postingCmd.amount(), postingCmd.currency());
            Posting posting = new Posting(postingCmd.accountId(), money, postingCmd.type());
            transaction.addPosting(posting);
        }
        transaction.validate(); // Business Rule: sum must be zero

        // 3. Update Accounts (Atomic balance update)
        for (Posting posting : transaction.getPostings()) {
            Account account = accountPort.loadLocked(posting.getAccountId())
                    .orElseThrow(() -> new IllegalArgumentException("Account not found: " + posting.getAccountId()));

            account.postPosting(posting);
            accountPort.save(account);
        }

        // 4. Save Transaction
        transactionPort.save(transaction);

        return transaction.getId();
    }

    @Override
    @Transactional
    public UUID transferFunds(TransferFundsCommand command) {
        // Construct the Postings
        PostingCommand creditSource = new PostingCommand(
                command.fromAccountId(),
                command.amount(),
                command.currency(),
                Posting.Type.CREDIT);

        PostingCommand debitDest = new PostingCommand(
                command.toAccountId(),
                command.amount(),
                command.currency(),
                Posting.Type.DEBIT);

        // Delegate to the generic PostTransaction logic
        PostTransactionCommand txCommand = new PostTransactionCommand(
                command.description() != null ? command.description() : "Transfer",
                java.util.List.of(creditSource, debitDest));

        return postTransaction(txCommand);
    }
}
